config/routes.rb
Rails.application.routes.draw do
  

  resources :books
  resources :users
  resources :sessions
  
  get 'welcome/index'

  root 'welcome#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
	has_many :users
end

app/models/book_issue.rb
class BookIssue < ActiveRecord::Base
	belongs_to :user
	belongs_to :book

	
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :books
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :name,  presence: true, length: {maximum: 30}
    validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
    validates :password, presence: true
    validates :password_confirmation, presence: true	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private
def current_user
	@current_user ||= User.find(session[:user_id]) if session[:user_id]
	
end
helper_method :current_user
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	def index
    @book = Book.all
  end

def new
 @book = Book.new
end

def create
  @book = Book.new(book_params)
 
  if @book.save
    redirect_to @book
  else
    render 'new'
  end
end

def show
    @book = Book.find(params[:id])
    @issue = BookIssue.where("book_id = ?" , params[:id]).count

end
private
  def book_params
    params.require(:book).permit(:title, :author, :total)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_email(params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to books_path, notice: "Logged in"
  	else
  		flash.now.alert ="Email or Password Incorrect"
  		render "new"
  	end
  end

  def destroy
    session.delete(:user_id)
  	@current_user = nil
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user =User.new(user_params)
		if @user.save
			redirect_to root_url, notice: "Signup Succesful"
		else
			render "new"
		end
	end
private 
def user_params
	params.require(:user).permit(:name, :email, :password, :password_confirmation)
end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/adminsessions_helper.rb
module AdminsessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/index.html.erb
<h1>Books List</h1>
Logged in as <%= current_user.name %>
<%= link_to "Log Out", session_path("current"), method: "delete" %>
<br><br><br>
<table>
  <tr>
    <th>Title</th>
    <th>Author</th>
    
  </tr>
 
  <% @book.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.author %></td>
      <td><%= link_to 'Show Available', book_path(book) %></td>
    </tr>
  <% end %>
</table>

app/views/books/new.html.erb
<%= form_for @book do |f| %>
 
  
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </p>

  <p>
    <%= f.label :total_copies %><br>
    <%= f.text_field :total %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/books/show.html.erb
Logged in as <%= current_user.name %>
<%= link_to "Log Out", session_path("current"), method: "delete" %>
<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>
 
<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p><strong>Currently Available:</strong>
  <%= @book.total-@issue %></p>

<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LibraryApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
	<h2>Signup Invalid</h2>
	<ul>
		<% @user.errors.full_messages.each do |msg| %>
		<li> <%= msg %></li>
	</ul>
	<% end %>
<% end %>
<p>
	<%= f.label :name %>
	<%= f.text_field :name %>
</p>	
<p>
	<%= f.label :email %>
	<%= f.text_field :email %>
</p>
<p>
	<%= f.label :password %>
	<%= f.password_field :password %>
</p>
<p>
	<%= f.label :password_confirmation %>
	<%= f.password_field :password_confirmation %>
</p>
   <%= f.submit %>
   <% end %>

app/views/welcome/index.html.erb
<h1>Welcome to library </h1>
<% if current_user %>
	Logged in as <%= current_user.name %>
	<%= link_to "Log Out", session_path("current"), method: "delete" %>
<% else %>	
	<%= link_to "Sign Up" , new_user_path %> or
	<%= link_to "Log In" , new_session_path %>
	

<% end %>